### ISSUE TITLE
Crash report

### ISSUE THREAD

**Issue by Anuuviem** [SKO85/SE-Mods#8]
I am unsure how to reproduce this issue. I have been fighting spontaneous, irregular, reportless crashes forever when I finally got this one. Have since removed the mod and no longer suffer any issues. The crashes were as spontaneous as 5min server uptime to 3hrs uptime.

20:04:59.5287 [DEBUG]  Keen: ERROR Entity init!: System.NullReferenceException: Object reference not set to an instance of an object.
   at System.Collections.Generic.Dictionary`2.Insert(TKey key, TValue value, Boolean add)
   at NaniteConstructionSystem.Entities.NaniteProjectorLogic.Init(MyObjectBuilder_EntityBase objectBuilder)
   at Sandbox.Game.Entities.MyCompositeGameLogicComponent.Init(MyObjectBuilder_EntityBase objectBuilder)
   at VRage.Game.Entity.MyEntity.Init(MyObjectBuilder_EntityBase objectBuilder)
   at Sandbox.Game.Entities.MyCubeBlock.Init(MyObjectBuilder_CubeBlock builder, MyCubeGrid cubeGrid)
   at Sandbox.Game.Entities.Cube.MyTerminalBlock.Init(MyObjectBuilder_CubeBlock objectBuilder, MyCubeGrid cubeGrid)
   at Sandbox.Game.Entities.Cube.MyFunctionalBlock.Init(MyObjectBuilder_CubeBlock objectBuilder, MyCubeGrid cubeGrid)
   at Patched_Sandbox.Game.Entities.Blocks.MyProjectorBaseInit_0(Object cubeGrid, MyObjectBuilder_CubeBlock , MyCubeGrid )
   at Sandbox.Game.Entities.Cube.MySlimBlock.Init(MyObjectBuilder_CubeBlock objectBuilder, MyCubeGrid cubeGrid, MyCubeBlock fatBlock)
   at Sandbox.Game.Entities.MyCubeGrid.AddCubeBlock_Patch1(MyCubeGrid this, MyObjectBuilder_CubeBlock objectBuilder, Boolean testMerge, MyCubeBlockDefinition blockDefinition)
   at Sandbox.Game.Entities.MyCubeGrid.AddBlock(MyObjectBuilder_CubeBlock objectBuilder, Boolean testMerge)
   at Sandbox.Game.Entities.MyCubeGrid.InitInternal(MyObjectBuilder_EntityBase objectBuilder, Boolean rebuildGrid)
   at Sandbox.Game.Entities.MyCubeGrid.Init(MyObjectBuilder_EntityBase objectBuilder)
   at Sandbox.Game.Entities.MyEntities.InitEntity(MyObjectBuilder_EntityBase objectBuilder, MyEntity& entity, Boolean tolerateBlacklistedPlanets)

**Comment by SKO85** [comment]
Hi @Anuuviem , thx for the report. I think this is another mod as I don't see the call happening in my mod. Seems that you are also using 'NaniteConstructionSystem` which is another mod. Can this be the case?
