### ISSUE TITLE
error from server

### ISSUE THREAD

**Issue by zeddyccus** [SKO85/SE-Mods#9]
Good morning,

I wanted to play again with your mod on my private server but I got the following error and I don't know where it's coming from

2024-10-20 14:24:04Z:ERROR: BuildAndRepairSystemBlock Small Grid 398.BuildAndRepairSystem 35: AsyncUpdateSourcesAndTargets exception at 4: System.ArgumentException: Unable to sort because the IComparer.Compare() method returns inconsistent results. Either a value does not compare equal to itself, or one value repeatedly compared to another value yields different results. IComparer: 'System.Array+FunctorComparer`1[SKONanobotBuildAndRepairSystem.TargetEntityData]'.
   at System.Collections.Generic.IntrospectiveSortUtilities.ThrowOrIgnoreBadComparer(Object comparer)
   at System.Collections.Generic.ArraySortHelper`1.Sort(T[] keys, Int32 index, Int32 length, IComparer`1 comparer)
   at System.Array.Sort[T](T[] array, Int32 index, Int32 length, IComparer`1 comparer)
   at System.Collections.Generic.List`1.Sort(Comparison`1 comparison)
   at SKONanobotBuildAndRepairSystem.NanobotBuildAndRepairSystemBlock.AsyncUpdateSourcesAndTargets(Boolean updateSource)

**Comment by SKO85** [comment]
Can you tell me if this is a local game, dedicated server or are you using Torch for the server with some additional plugins. Also, are you using some other mods in combination with this one?
